name: Test API STAC (Run Forzato 23/07/2026)

on:
  workflow_dispatch:

jobs:
  run_stac_test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: meteo-stac
          python-version: "3.10"
          channels: conda-forge, defaults
          channel-priority: strict
          auto-activate-base: false

      - name: Install Metview and Dependencies
        run: |
          conda install -y -c conda-forge metview-batch metview-python eccodes requests numpy pandas matplotlib

      - name: Clone COSMO and ECMWF GRIB Definitions
        run: |
          mkdir -p grib_definitions
          cd grib_definitions
          git clone https://github.com/COSMO-ORG/eccodes-cosmo-resources.git
          git clone https://github.com/ecmwf/eccodes.git
          cd ..

      - name: Esegui Python Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # Set the GRIB format local definitions of the COSMO consortium
          GRIB_DEFINITION_PATH: ${{ github.workspace }}/grib_definitions/eccodes-cosmo-resources/definitions:${{ github.workspace }}/grib_definitions/eccodes/definitions
        run: |
          python icon_ch2_ens_map.py
